import numpy as np, pandas as pd, sqlite3, json
from pathlib import Path
rng = np.random.default_rng(42)
D = Path("data"); D.mkdir(exist_ok=True)

# ---------- customers ----------
n = 1000
cust = pd.DataFrame({
    "customer_id": [f"C{100000+i}" for i in range(n)],
    "age": rng.integers(19, 75, n),
    "annual_income": np.round(rng.lognormal(11.0, 0.45, n), -2).astype(int),
    "employment_status": rng.choice(["Full-time","Part-time","Self-employed","Retired","Unemployed"], n, p=[.55,.15,.15,.1,.05]),
    "region": rng.choice(["North","South","East","West"], n),
})
cust["customer_since"] = pd.to_datetime("2010-01-01") + pd.to_timedelta(rng.integers(0, 5000, n), unit="D")

# ---------- accounts ----------
m = 2000
acc = pd.DataFrame({
    "account_id": [f"A{500000+i}" for i in range(m)],
    "customer_id": rng.choice(cust.customer_id, m),
    "product": rng.choice(["Credit Card","Personal Loan"], m, p=[.6,.4]),
    "open_date": pd.to_datetime("2019-01-01") + pd.to_timedelta(rng.integers(0, 1800, m), unit="D"),
    "credit_limit": rng.choice([2000,5000,8000,10000,15000,25000], m),
})
acc["balance"] = np.round(acc.credit_limit * rng.beta(2, 3, m), 2)
acc["utilisation"] = np.round(acc.balance / acc.credit_limit, 4)
acc["bureau_score"] = np.clip(rng.normal(680, 90, m), 300, 900).round().astype(int)
acc["days_past_due"] = np.where(rng.random(m) < .18, rng.choice([5,15,30,45,60,90,120], m), 0)
logit = -3.2 + 2.2*acc.utilisation - 0.006*(acc.bureau_score-680) + 0.012*acc.days_past_due
acc["default_flag"] = (rng.random(m) < 1/(1+np.exp(-logit))).astype(int)

# 1. clean CSV
acc.to_csv(D/"credit_accounts.csv", index=False)

# 2. messy CSV (metadata header, comments, currency text, dd/mm/yyyy, odd NA markers, footer)
msy = acc.head(300).copy()
msy["open_date"] = msy.open_date.dt.strftime("%d/%m/%Y")
msy["credit_limit"] = msy.credit_limit.map(lambda v: f"${v:,.0f}")
msy["balance"] = msy.balance.map(lambda v: f"${v:,.2f}")
msy = msy[["account_id","customer_id","product","open_date","credit_limit","balance","bureau_score","days_past_due","default_flag"]]
for c in ["bureau_score","days_past_due","product"]:
    msy[c] = msy[c].astype(object)
for col, mark in [("bureau_score","N/A"),("days_past_due","-"),("product","?")]:
    idx = rng.choice(msy.index, 12, replace=False); msy.loc[idx, col] = mark
body = msy.to_csv(index=False)
lines = body.strip().split("\n")
lines.insert(5, "# --- data quality note: rows below migrated from legacy system ---")
with open(D/"credit_accounts_messy.csv","w") as f:
    f.write("Report: Credit Accounts Extract\nGenerated by: Risk Data Warehouse\nSource system: LEGACY_CC_V2\n")
    f.write("\n".join(lines) + "\nTotal rows: 300\n")

# 3. pipe-delimited text, no header
pay = pd.DataFrame({
    "account_id": rng.choice(acc.account_id, 3000),
    "pay_date": (pd.to_datetime("2024-01-01") + pd.to_timedelta(rng.integers(0, 365, 3000), unit="D")).strftime("%Y-%m-%d"),
    "amount": np.round(rng.gamma(2, 150, 3000), 2),
    "channel": rng.choice(["BPAY","DirectDebit","Card","Branch"], 3000),
})
pay.to_csv(D/"repayments_pipe.txt", sep="|", header=False, index=False)

# 4. fixed-width text (bureau report): id(0-7) name(7-27) score(27-30) enq(30-32) status(32-40)
fw = acc.head(60)
with open(D/"bureau_report_fixed_width.txt","w") as f:
    for i, r in fw.iterrows():
        f.write(f"{r.account_id:<7}" + f"{'Customer '+str(i):<20}" + f"{r.bureau_score:>3}" + f"{rng.integers(0,12):>2}" + f"{rng.choice(['OPEN','CLOSED','ARREARS']):<8}\n")

# 5. Excel workbook with several sheets (header offset on one)
with pd.ExcelWriter(D/"portfolio_report.xlsx") as xw:
    pd.DataFrame({"README":["Portfolio report Q3","Sheets: Accounts, Monthly_Summary, Collections","Accounts table starts on row 4 (title rows above it)"]}).to_excel(xw, sheet_name="README", index=False)
    acc.head(500).to_excel(xw, sheet_name="Accounts", index=False, startrow=3)
    ms = pd.DataFrame({"month": pd.period_range("2024-01", periods=12, freq="M").astype(str),
                       "new_accounts": rng.integers(80,160,12), "defaults": rng.integers(5,40,12),
                       "exposure_mm": np.round(rng.uniform(40,60,12),1)})
    ms.to_excel(xw, sheet_name="Monthly_Summary", index=False)
    col = pd.DataFrame({"account_id": rng.choice(acc.account_id, 150, replace=False),
                        "stage": rng.choice(["Early","Mid","Late","Legal"], 150),
                        "amount_recovered": np.round(rng.gamma(2, 400, 150),2)})
    col.to_excel(xw, sheet_name="Collections", index=False)

# 6. JSON: records + nested
recs = []
for _, r in cust.iterrows():
    recs.append({"customer_id": r.customer_id, "age": int(r.age),
                 "profile": {"employment_status": r.employment_status, "annual_income": int(r.annual_income), "region": r.region},
                 "contacts": [{"type":"email","verified": bool(rng.random()<.8)}, {"type":"mobile","verified": bool(rng.random()<.9)}],
                 "customer_since": r.customer_since.strftime("%Y-%m-%d")})
json.dump(recs, open(D/"customers_nested.json","w"), indent=1)
cust.assign(customer_since=cust.customer_since.dt.strftime("%Y-%m-%d")).to_json(D/"customers_flat.json", orient="records", indent=1)
cust.assign(customer_since=cust.customer_since.dt.strftime("%Y-%m-%d")).head(200).to_json(D/"customers.jsonl", orient="records", lines=True)

# 7. SQLite database (stand-in for SQL Server)
con = sqlite3.connect(D/"credit_risk.db")
cust.assign(customer_since=cust.customer_since.dt.strftime("%Y-%m-%d")).to_sql("customers", con, index=False, if_exists="replace")
acc.assign(open_date=acc.open_date.dt.strftime("%Y-%m-%d")).to_sql("accounts", con, index=False, if_exists="replace")
pay.to_sql("payments", con, index=False, if_exists="replace")
con.close()
print("done", sorted(p.name for p in D.iterdir()))
print(acc.default_flag.mean())
