# Python Data Types Deep Practice — Lists
### 30 Questions, Progressive Difficulty

Same rules as before: attempt first, don't peek early, run your own cell before the solution cell.

---

## Part A: Creating, Indexing & Slicing (Q1-Q7)

**Q1** Create a list `scores = [720, 610, 800, 590, 700]`. Print the first element and the last element.

In [2]:
# YOUR CODE HERE
score=[720,610,800,590,700]
score[0],score[-1]


(720, 700)

**Solution 1**

In [ ]:
scores = [720, 610, 800, 590, 700]
print(scores[0])
print(scores[-1])

**Q2** From `scores`, print the first 3 elements using slicing, then the last 2 elements using slicing.

In [10]:
# YOUR CODE HERE
print(score[:3])
print(score[-2:])

[720, 610, 800]
[590, 700]


**Solution 2**

In [6]:
scores = [720, 610, 800, 590, 700]
print(scores[:3])
print(scores[-2:])

[720, 610, 800]
[590, 700]


**Q3** Given `scores`, reverse the list using slicing (no `.reverse()` or `reversed()`).

In [ ]:
# YOUR CODE HERE
scores[::-1]

AttributeError: 'list' object has no attribute 'reversed'

**Solution 3**

In [ ]:
scores = [720, 610, 800, 590, 700]
print(scores[::-1])


**Q4** Create an empty list `high_risk = []`. Use `.append()` to add three scores below 650 one at a time.

In [20]:
# YOUR CODE HERE
high_risk=[]
high_risk.append(590)
high_risk.append(600)
high_risk

[590, 600]

**Solution 4**

In [ ]:
high_risk = []
high_risk.append(600)
high_risk.append(590)
high_risk.append(620)
print(high_risk)

**Q5** Given `names = ["Alice", "Bob"]`, use `.insert()` to add `"Cara"` at index 1 (between Alice and Bob).

In [24]:
# YOUR CODE HERE
names=['Alice','Bob']
names.insert(1,'Cara')
print(names)

['Alice', 'Cara', 'Bob']


**Solution 5**

In [ ]:
names = ["Alice", "Bob"]
names.insert(1, "Cara")
print(names)

**Q6** Given `defaults = [1, 0, 1, 1, 0]`, check whether the value `1` exists using the `in` keyword. Then find its first index using `.index()`.

In [27]:
# YOUR CODE HERE
defaults=[1,0,1,1,0]
defaults.index(1)

0

**Solution 6**

In [ ]:
defaults = [1, 0, 1, 1, 0]
print(1 in defaults)
print(defaults.index(1))

**Q7** Given a nested list `transactions = [["Alice", 500], ["Bob", 1200], ["Cara", 300]]`, print just Bob's transaction amount (access the nested element directly).

In [28]:
# YOUR CODE HERE
transactions=[["Alice", 500], ["Bob", 1200], ["Cara", 300]]
transactions[1][1]

1200

**Solution 7**

In [ ]:
transactions = [["Alice", 500], ["Bob", 1200], ["Cara", 300]]
print(transactions[1][1])

## Part B: Modifying Lists (Q8-Q14)

**Q8** Given `balances = [1000, 2000, 3000]`, update the second element to `2500` by direct index assignment.

In [29]:
# YOUR CODE HERE
balances=[1000,2000,3000]
balances[1]=2500
balances

[1000, 2500, 3000]

**Solution 8**

In [ ]:
balances = [1000, 2000, 3000]
balances[1] = 2500
print(balances)

**Q9** Given `pending = ["loan_a", "loan_b", "loan_c"]`, remove `"loan_b"` using `.remove()`.

In [31]:
# YOUR CODE HERE
pending = ["loan_a", "loan_b", "loan_c"]
pending.remove('loan_b')
print(pending)

['loan_a', 'loan_c']


**Solution 9**

In [ ]:
pending = ["loan_a", "loan_b", "loan_c"]
pending.remove("loan_b")
print(pending)

**Q10** Given `queue = [10, 20, 30, 40]`, remove and print the last item using `.pop()`, then remove and print the item at index 0 using `.pop(0)`.

In [34]:
# YOUR CODE HERE
queue=[10,20,30,40]
queue.pop(0)

10

**Solution 10**

In [ ]:
queue = [10, 20, 30, 40]
last = queue.pop()
print(last, queue)
first = queue.pop(0)
print(first, queue)

**Q11** Given `codes = ["B", "A", "C"]`, sort it alphabetically in place using `.sort()`, then print it. Then sort `nums = [5, 2, 9, 1]` in descending order using `.sort(reverse=True)`.

In [42]:
# YOUR CODE HERE
codes=['B','A','C']
codes.sort()
codes
nums=[5,2,9,1]
nums.sort(reverse='TrUe')
nums

[9, 5, 2, 1]

**Solution 11**

In [ ]:
codes = ["B", "A", "C"]
codes.sort()
print(codes)

nums = [5, 2, 9, 1]
nums.sort(reverse=True)
print(nums)

**Q12** Given `raw_scores = [720, 610, 800]`, create a NEW sorted list using `sorted()` without modifying the original. Print both to prove the original is unchanged.

In [44]:
# YOUR CODE HERE
raw_scores=[720,610,800]
new_list=sorted(raw_scores)
print(raw_scores,new_list)

[720, 610, 800] [610, 720, 800]


**Solution 12**

In [ ]:
raw_scores = [720, 610, 800]
new_sorted = sorted(raw_scores)
print(raw_scores)
print(new_sorted)

**Q13** Given `combo = [1, 2, 3]` and `extra = [4, 5, 6]`, combine them into one list two ways: using `+` and using `.extend()`.

In [47]:
# YOUR CODE HERE
combo=[1,2,3]
extra=[4,5,6]
combo.extend(extra)
combo


[1, 2, 3, 4, 5, 6]

**Solution 13**

In [ ]:
combo = [1, 2, 3]
extra = [4, 5, 6]
combined_plus = combo + extra
print(combined_plus)

combo2 = [1, 2, 3]
combo2.extend(extra)
print(combo2)

**Q14** Given `duplicate_ids = [101, 102, 101, 103, 102]`, remove duplicates while keeping only unique values (order doesn't matter — use a set conversion).

In [48]:
# YOUR CODE HERE
duplicate_ids = [101, 102, 101, 103, 102]
unique=list(set(duplicate_ids))
unique

[101, 102, 103]

**Solution 14**

In [ ]:
duplicate_ids = [101, 102, 101, 103, 102]
unique_ids = list(set(duplicate_ids))
print(unique_ids)

## Part C: Looping & Comprehensions (Q15-Q22)

**Q15** Given `scores = [720, 610, 800, 590, 700]`, loop through and print only the scores above 650.

In [50]:
# YOUR CODE HERE
score
for i in score:
    if i>650:
        print(i)

720
800
700


**Solution 15**

In [ ]:
scores = [720, 610, 800, 590, 700]
for s in scores:
    if s > 650:
        print(s)

**Q16** Rewrite Q15 as a single list comprehension that returns a list of scores above 650 (instead of printing one by one).

In [51]:
# YOUR CODE HERE
[i for i in score if i>650]

[720, 800, 700]

**Solution 16**

In [2]:
scores = [720, 610, 800, 590, 700]
above_650 = [s for s in scores if s > 650]
print(above_650)

[720, 800, 700]


**Q17** Given `scores`, use a list comprehension to create a list of `"Pass"`/`"Fail"` labels: `"Pass"` if score >= 650, else `"Fail"`.

In [3]:
# YOUR CODE HERE
['Pass' if s>=650 else 'Fail' for s in scores]

['Pass', 'Fail', 'Pass', 'Fail', 'Pass']

**Solution 17**

In [ ]:
scores = [720, 610, 800, 590, 700]
labels = ["Pass" if s >= 650 else "Fail" for s in scores]
print(labels)

**Q18** Given `scores`, use `enumerate()` in a loop to print each score along with its position, e.g. `"Customer 0: 720"`.

In [8]:
# YOUR CODE HERE
for i,s in enumerate(scores):
    print(f'Customer {i}:{s}')

Customer 0:720
Customer 1:610
Customer 2:800
Customer 3:590
Customer 4:700


**Solution 18**

In [ ]:
scores = [720, 610, 800, 590, 700]
for i, s in enumerate(scores):
    print(f"Customer {i}: {s}")

**Q19** Given ``names = ["Alice", "Bob", "Cara"]` and `scores = [720, 610, 800]``, use `zip()` to loop through both together and print `"Alice: 720"` style output.

In [11]:
# YOUR CODE HERE
names = ["Alice", "Bob", "Cara"]
scores = [720, 610, 800]
zip(names,scores)
for n,s in zip(names,scores):
    print(f'name is {n} and score is {s}')

name is Alice and score is 720
name is Bob and score is 610
name is Cara and score is 800


**Solution 19**

In [ ]:
names = ["Alice", "Bob", "Cara"]
scores = [720, 610, 800]
for n, s in zip(names, scores):
    print(f"{n}: {s}")

**Q20** Using the same `names` and `scores`, build a dictionary `{name: score}` using a single line combining `zip()` and `dict()`.

In [12]:
# YOUR CODE HERE
new_dic=dict(zip(names,scores))
new_dic

{'Alice': 720, 'Bob': 610, 'Cara': 800}

**Solution 20**

In [ ]:
names = ["Alice", "Bob", "Cara"]
scores = [720, 610, 800]
name_score = dict(zip(names, scores))
print(name_score)

**Q21** Given `amounts = [100, -50, 200, -30, 400]` (negative = refund), use a list comprehension to get only the positive charges.

In [14]:
# YOUR CODE 
amounts=[100,-50,200,-30,400]
[amt for amt in amounts if amt>0]

[100, 200, 400]

**Solution 21**

In [ ]:
amounts = [100, -50, 200, -30, 400]
charges = [a for a in amounts if a > 0]
print(charges)

**Q22** Given `matrix = [[1,2,3],[4,5,6],[7,8,9]]` (rows = customers, columns = monthly payments), use a nested list comprehension to flatten it into a single list.

In [1]:
# YOUR CODE HERE
matrix=[[1,2,3],[4,5,6],[7,8,9]]
[val for row in matrix for val in row]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

**Solution 22**

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
flat = [val for row in matrix for val in row]
print(flat)

## Part D: Aggregation & Built-ins (Q23-Q27)

**Q23** Given `balances = [1200, 3400, 500, 8900, 200]`, find the `sum()`, `max()`, `min()`, and average (compute manually) in one cell.

In [ ]:
# YOUR CODE HERE


**Solution 23**

In [ ]:
balances = [1200, 3400, 500, 8900, 200]
total = sum(balances)
highest = max(balances)
lowest = min(balances)
average = total / len(balances)
print(total, highest, lowest, average)

**Q24** Given `defaults = [1, 0, 1, 1, 0, 0, 1]` (1 = defaulted), calculate the default rate as a percentage using `sum()` and `len()`.

In [ ]:
# YOUR CODE HERE


**Solution 24**

In [ ]:
defaults = [1, 0, 1, 1, 0, 0, 1]
default_rate = sum(defaults) / len(defaults) * 100
print(f"{default_rate:.2f}%")

**Q25** Given `scores = [720, 610, 800, 590, 700]`, use `sorted()` with `reverse=True` to get the top 3 scores using slicing.

In [ ]:
# YOUR CODE HERE


**Solution 25**

In [ ]:
scores = [720, 610, 800, 590, 700]
top_3 = sorted(scores, reverse=True)[:3]
print(top_3)

**Q26** Given `all_scores = [720, 610, 800, 590, 700, 650, 680]`, use `any()` to check if ANY score is below 600, and `all()` to check if ALL scores are above 500.

In [ ]:
# YOUR CODE HERE


**Solution 26**

In [ ]:
all_scores = [720, 610, 800, 590, 700, 650, 680]
print(any(s < 600 for s in all_scores))
print(all(s > 500 for s in all_scores))

**Q27** Given `risk_levels = ["Low", "High", "Medium", "High", "Low", "High"]`, count how many times `"High"` appears using `.count()`.

In [ ]:
# YOUR CODE HERE


**Solution 27**

In [ ]:
risk_levels = ["Low", "High", "Medium", "High", "Low", "High"]
print(risk_levels.count("High"))

## Part E: Mini Challenges (Q28-Q30)

**Q28** Given customer records as a list of tuples:
```python
records = [("Alice", 720, 15000), ("Bob", 610, 8000), ("Cara", 800, 22000)]
```
Loop through and print a formatted line for each: name, risk category (>=750 Low, >=650 Medium, else High), and balance formatted as currency.

In [ ]:
# YOUR CODE HERE


**Solution 28**

In [ ]:
records = [("Alice", 720, 15000), ("Bob", 610, 8000), ("Cara", 800, 22000)]

for name, score, balance in records:
    if score >= 750:
        risk = "Low"
    elif score >= 650:
        risk = "Medium"
    else:
        risk = "High"
    print(f"{name}: {risk} Risk, Balance: ${balance:,.2f}")

**Q29** Given `records` from Q28, build a list comprehension that returns only the names of customers with "High" risk (score < 650).

In [ ]:
# YOUR CODE HERE


**Solution 29**

In [ ]:
records = [("Alice", 720, 15000), ("Bob", 610, 8000), ("Cara", 800, 22000)]
high_risk_names = [name for name, score, balance in records if score < 650]
print(high_risk_names)

**Q30** Given two lists representing this month's and last month's defaulted customer IDs:
```python
this_month = [101, 102, 105, 107]
last_month = [102, 103, 105]
```
Find: (a) customers who defaulted in both months, (b) customers who are NEW defaulters this month (in this_month but not last_month). Use set operations.

In [ ]:
# YOUR CODE HERE


**Solution 30**

In [ ]:
this_month = [101, 102, 105, 107]
last_month = [102, 103, 105]

both_months = set(this_month) & set(last_month)
new_defaulters = set(this_month) - set(last_month)

print("Defaulted both months:", both_months)
print("New defaulters:", new_defaulters)

---
## Checkpoint

30 questions across indexing/slicing, modifying, looping/comprehensions, aggregation, and mini real-world challenges combining tuples, dicts, and sets with lists.

When you're comfortable with lists, say the word and I'll build the next one: **Dictionaries deep practice** (this one matters a lot for pandas later, since rows/records map naturally to dicts).