# Python Data Types Deep Practice — Tuples
### 20 Questions

Shorter set since you've already brushed against tuples in earlier notebooks. Same rules: attempt first, then compare.

---

## Part A: Creating & Accessing (Q1-Q6)

**Q1** Create a tuple `record = ("Alice", 720, 15000)` representing (name, score, balance). Print each element by index.

In [4]:
# YOUR CODE HERE
record=('Alice',720,15000)
type(record)
record[0]

'Alice'

**Solution 1**

In [ ]:
record = ("Alice", 720, 15000)
print(record[0])
print(record[1])
print(record[2])

**Q2** Unpack `record` directly into three variables `name, score, balance` in one line, then print them.

In [6]:
# YOUR CODE HERE
name,score,balance=record
score

720

**Solution 2**

In [ ]:
record = ("Alice", 720, 15000)
name, score, balance = record
print(name, score, balance)

**Q3** Try to change `record[1]` to `730` and observe what happens — write your observation as a comment after catching the error with try/except.

In [9]:
# YOUR CODE HERE
try:
    record[1]=730
except Exception as e:
    print(e)

'tuple' object does not support item assignment


**Solution 3**

In [ ]:
record = ("Alice", 720, 15000)
try:
    record[1] = 730
except TypeError as e:
    print("Error:", e)
    # Tuples are immutable — you cannot change elements after creation.

TypeError: 'tuple' object does not support item assignment

**Q4** Create a single-element tuple `single = (720,)` (note the trailing comma) and print its type to confirm it's a tuple, not just an int.

In [12]:
# YOUR CODE HERE
single=(720,)
type(single)

tuple

**Solution 4**

In [ ]:
single = (720,)
print(type(single))

**Q5** Given `record = ("Alice", 720, 15000)`, get its length using `len()`, and check if `720` is in it using `in`.

In [15]:
# YOUR CODE HERE
len(record)
720 in record

True

**Solution 5**

In [ ]:
record = ("Alice", 720, 15000)
print(len(record))
print(720 in record)

**Q6** Create a tuple without parentheses at all (just comma-separated values): `coords = 10, 20`. Print it and its type to confirm Python still makes it a tuple.

In [19]:
# YOUR CODE HERE
coords=10,20
a=type(coords)
print(a)

<class 'tuple'>


**Solution 6**

In [20]:
coords = 10, 20
print(coords, type(coords))

(10, 20) <class 'tuple'>


## Part B: Tuples in Practice (Q7-Q14)

**Q7** Given a list of tuples `records = [("Alice", 720), ("Bob", 610), ("Cara", 800)]`, loop through and print each name and score using unpacking in the for loop.

In [21]:
# YOUR CODE HERE
records = [("Alice", 720), ("Bob", 610), ("Cara", 800)]
for i,j in records:
    print(i,j)

Alice 720
Bob 610
Cara 800


**Solution 7**

In [ ]:
records = [("Alice", 720), ("Bob", 610), ("Cara", 800)]
for name, score in records:
    print(name, score)

**Q8** Given `records` from Q7, use a list comprehension to build a list of just the names where score >= 700.

In [ ]:
# YOUR CODE HERE


**Solution 8**

In [ ]:
records = [("Alice", 720), ("Bob", 610), ("Cara", 800)]
qualified = [name for name, score in records if score >= 700]
print(qualified)

**Q9** Write a function `min_max(numbers)` that returns a tuple `(min_value, max_value)` given a list. Call it with `[720, 610, 800, 590]` and unpack the result into two variables.

In [ ]:
# YOUR CODE HERE


**Solution 9**

In [ ]:
def min_max(numbers):
    return (min(numbers), max(numbers))

lo, hi = min_max([720, 610, 800, 590])
print(lo, hi)

**Q10** Use tuple unpacking with a throwaway variable `_` to swap two variables `a = 5` and `b = 10` WITHOUT a temp variable (Python tuple-swap trick).

In [ ]:
# YOUR CODE HERE


**Solution 10**

In [ ]:
a = 5
b = 10
a, b = b, a
print(a, b)

**Q11** Given `record = ("Alice", 720, 15000, "Approved", "2024-01-15")`, use extended unpacking to grab the first element as `name`, the last element as `status_date`, and everything in between as a list called `middle`. (Hint: `name, *middle, status_date = record`)

In [ ]:
# YOUR CODE HERE


**Solution 11**

In [ ]:
record = ("Alice", 720, 15000, "Approved", "2024-01-15")
name, *middle, status_date = record
print(name)
print(middle)
print(status_date)

**Q12** Given two lists `names = ["Alice", "Bob"]` and `scores = [720, 610]`, use `zip()` to create a list of tuples pairing them, then convert that zip object to a list and print it.

In [ ]:
# YOUR CODE HERE


**Solution 12**

In [ ]:
names = ["Alice", "Bob"]
scores = [720, 610]
paired = list(zip(names, scores))
print(paired)

**Q13** Given `paired` (a list of tuples) from Q12, convert it into a dictionary using `dict()`.

In [ ]:
# YOUR CODE HERE


**Solution 13**

In [ ]:
names = ["Alice", "Bob"]
scores = [720, 610]
paired = list(zip(names, scores))
as_dict = dict(paired)
print(as_dict)

**Q14** Create a set of tuples to represent unique (customer_id, month) pairs that have already been billed: `billed = {(101, "Jan"), (102, "Jan"), (101, "Feb")}`. Check whether `(101, "Jan")` is in the set.

In [ ]:
# YOUR CODE HERE


**Solution 14**

In [ ]:
billed = {(101, "Jan"), (102, "Jan"), (101, "Feb")}
print((101, "Jan") in billed)

## Part C: Sorting & Mini Challenges (Q15-Q20)

**Q15** Given `records = [("Alice", 720), ("Bob", 610), ("Cara", 800)]`, sort by score (the second tuple element) ascending using `sorted()` with `key=lambda x: x[1]`.

In [ ]:
# YOUR CODE HERE


**Solution 15**

In [ ]:
records = [("Alice", 720), ("Bob", 610), ("Cara", 800)]
sorted_records = sorted(records, key=lambda x: x[1])
print(sorted_records)

**Q16** Sort the same `records` by score DESCENDING (highest score first).

In [ ]:
# YOUR CODE HERE


**Solution 16**

In [ ]:
records = [("Alice", 720), ("Bob", 610), ("Cara", 800)]
sorted_records = sorted(records, key=lambda x: x[1], reverse=True)
print(sorted_records)

**Q17** Given `records = [("Alice", 720, 15000), ("Bob", 610, 8000), ("Cara", 800, 22000)]`, sort by score but if two scores tie, sort by balance descending as a secondary key. (Use a tuple key: `key=lambda x: (x[1], -x[2])`)

In [ ]:
# YOUR CODE HERE


**Solution 17**

In [ ]:
records = [("Alice", 720, 15000), ("Bob", 610, 8000), ("Cara", 800, 22000)]
sorted_records = sorted(records, key=lambda x: (x[1], -x[2]), reverse=True)
print(sorted_records)

**Q18** Write a function `loan_summary(name, score, amount)` that returns a NAMED tuple-like result using Python's `collections.namedtuple`. Create one instance and access its fields by name (e.g. `result.score`).

In [ ]:
# YOUR CODE HERE


**Solution 18**

In [ ]:
from collections import namedtuple

LoanSummary = namedtuple("LoanSummary", ["name", "score", "amount"])

def loan_summary(name, score, amount):
    return LoanSummary(name, score, amount)

result = loan_summary("Alice", 720, 15000)
print(result.name, result.score, result.amount)

**Q19** Given monthly balance snapshots as tuples `(month, balance)`:
```python
history = [("Jan", 5000), ("Feb", 4500), ("Mar", 4000), ("Apr", 4200)]
```
Calculate the month-over-month change for each pair of consecutive months, printing e.g. `"Jan->Feb: -500"`.

In [ ]:
# YOUR CODE HERE


**Solution 19**

In [ ]:
history = [("Jan", 5000), ("Feb", 4500), ("Mar", 4000), ("Apr", 4200)]

for i in range(len(history) - 1):
    month1, bal1 = history[i]
    month2, bal2 = history[i + 1]
    change = bal2 - bal1
    print(f"{month1}->{month2}: {change:+}")

**Q20** Combine it all: given a list of applicant tuples `(name, score, requested_amount)`:
```python
applicants = [
    ("Alice", 720, 15000),
    ("Bob", 610, 8000),
    ("Cara", 800, 22000),
    ("Dave", 590, 5000),
]
```
Build a list of tuples `(name, decision)` where decision is `"Approved"` if score >= 650 AND requested_amount <= 20000, else `"Declined"`. Print the result sorted by name.

In [ ]:
# YOUR CODE HERE


**Solution 20**

In [ ]:
applicants = [
    ("Alice", 720, 15000),
    ("Bob", 610, 8000),
    ("Cara", 800, 22000),
    ("Dave", 590, 5000),
]

decisions = [
    (name, "Approved" if score >= 650 and amount <= 20000 else "Declined")
    for name, score, amount in applicants
]

decisions_sorted = sorted(decisions, key=lambda x: x[0])
print(decisions_sorted)

---
## Checkpoint

20 questions covering creation/immutability, unpacking (including extended unpacking with `*`), tuples-as-dict-source, sorting by tuple keys (multi-level sort — a preview of pandas `sort_values` with multiple columns), and `namedtuple`.

Next: **sets deep practice** (also shorter), or straight to pandas if you're ready to move on.